<?php
/* Ubercart Hex Value Attribute, created by Luke Tarplin, luket@ukvoipnet.com */

/* Form Alter Hook */
function uc_color_attribute_form_alter(&$form, &$form_state, $form_id){
	if($form_id == "uc_attribute_option_form"){
		if($form['#parameters'][2]->name == "colorChoice"){
			/* We have the Colour Form */
			if($form_state['post']['op'] == t("Submit")){
				uc_color_attribute_save($form_state['post']['hexcolor']);
			}

			$arg5 = arg(5);
			if(!empty($arg5)){
				if(is_numeric($arg5)){
					$check = db_result(db_query("select hexValue from {uc_color_attribute} where oid = %d limit 1;", check_plain($arg5)));
					if(!empty($check)){
						$default_HexColor = $check;
					}else{
						$default_HexColor = variable_get('sample_color', '#000000');
					}
				}else{
					$default_HexColor = variable_get('sample_color', '#000000');
				}
			}

			/* Check Colour Picker Version Exists */
  			$color_field_type = (function_exists('colorpicker_2_or_later') ? 'colorpicker_' : '') .'textfield';
			$form['hexcolor'] = array(
    				'#type' => $color_field_type,
   				'#title' => t('Color Picker'),
    				'#description' => t('Please select a color from the colour picker.'),
    				'#default_value' => $default_HexColor,
				'#attributes' => array('width' => '200')
			);
		}
	}else if($form_id == "uc_product_add_to_cart_form_" . arg(1)){
		if(arg(0) == "node" && is_numeric(arg(1)) && ! arg(2)){
			$node = node_load(arg(1));
			if(!empty($node->attributes)){
				foreach($node->attributes as $value){
					if($value->name == "colorChoice"){
						/* We have a colour attribute choice */
						drupal_add_css(drupal_get_path('module', 'uc_color_attribute') . '/css/uc_color_attribute.css');
						drupal_add_js(drupal_get_path('module', 'uc_color_attribute') . '/js/uc_color_attribute.js');

						$attId = $value->aid;
						$html = "<div id='colors-background'>";

						foreach($form['attributes'][$attId]['#options'] as $key => $value){
							$kexValue = db_result(db_query("select hexValue from {uc_color_attribute} where oid = %d limit 1;",check_plain($key)));
							if(!empty($kexValue)){
								$html .= "<div style='background-color:".$kexValue.";' class='colors-color' title='".$value."' oId='".$key."' attrId='".$attId."'></div>";
							}
						}

						$html .= "</div><div style='clear:both;'></div>";
						$form['attributes'][$attId]['#prefix'] = $html;
					}
				}
			}
		}
	}
	return $form;
}

/* Form Submit Hook */
function uc_color_attribute_save($hexValue){
	/* Save value in the database */
	$arg5 = arg(5);
		if(!empty($arg5)){
			if(is_numeric($arg5)){
				db_query("update {uc_color_attribute} set hexValue = '%s' where oid = %d limit 1;",check_plain($hexValue),check_plain($arg5));
			}else{
				$lastId = db_fetch_object(db_query("show table status like '{uc_attribute_options}';"));
				db_query("insert into {uc_color_attribute} (aid,oid,hexValue) VALUES (%d,%d,'%s');",check_plain(arg(3)),$lastId->Auto_increment,check_plain($hexValue));
			}
		}
	return;
}

?>