<?php
/* Ubercart Hex Value Attribute, created by Luke Tarplin, luket@ukvoipnet.com */

/* Form Alter Hook */
function uc_color_attribute_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "uc_attribute_option_form"){
    if($form['#parameters'][2]->name == "colorChoice"){
      /* We have the Color Form */
      if($form_state['post']['op'] == t("Submit")){
        uc_color_attribute_save($form_state['post']['hexcolor']);
      }

      $arg5 = arg(5);
      if(!empty($arg5)){
        if(is_numeric($arg5)){
          $check = db_result(db_query("select hexValue from {uc_color_attribute} where oid = %d limit 1;", check_plain($arg5)));
          if(!empty($check)){
            $default_HexColor = $check;
          }else{
            $default_HexColor = variable_get('sample_color', '#000000');
          }
        }else{
          $default_HexColor = variable_get('sample_color', '#000000');
        }
      }

      /* Check Color Picker Version Exists */
        $color_field_type = (function_exists('colorpicker_2_or_later') ? 'colorpicker_' : '') .'textfield';
      $form['hexcolor'] = array(
            '#type' => $color_field_type,
            '#title' => t('Color Picker'),
            '#description' => t('Please select a color from the color picker.'),
            '#default_value' => $default_HexColor,
        '#attributes' => array('width' => '200')
      );
    }
  }else if($form_id == "uc_product_add_to_cart_form_" . arg(1)){
    if(arg(0) == "node" && is_numeric(arg(1)) && ! arg(2)){
      $node = node_load(arg(1));
      if(!empty($node->attributes)){
        foreach($node->attributes as $value){
          if($value->name == "colorChoice"){
            /* We have a color attribute choice */
            drupal_add_css(drupal_get_path('module', 'uc_color_attribute') . '/css/uc_color_attribute.css');
            drupal_add_js(drupal_get_path('module', 'uc_color_attribute') . '/js/uc_color_attribute.js');

            $attrId = $value->aid;
            $html = "<div id='uc-color-attribute-$attrId' class='uc-color-attribute'>";

            // colorChoice attribute label
            $html .= '<div class="form-item"><label>' . $value->label . ':';
            if ($value->required) {
              $html .= '<span class="form-required" title="This field is required.">*</span>';
            }
            $html .= "</label></div><!-- /form-item -->";

            // Helps us select the correct color if we are re-displaying
            // the form...such as when there is a form error.
            $selected_option = -1;
            if (is_array($form_state['post']['attributes'][$attrId])) {
              $selected_option = array_pop($form_state['post']['attributes'][$attrId]);
            }

            foreach($form['attributes'][$attrId]['#options'] as $key => $value){
              $kexValue = db_result(db_query("select hexValue from {uc_color_attribute} where oid = %d limit 1;",check_plain($key)));
              if(!empty($kexValue)){
                $selected_class = ($selected_option == $key) ? 'selected-color' : '';
                $html .= "<div style='background-color:".$kexValue.";' class='colors-color $selected_class' title='".$value."' oId='".$key."' attrId='".$attrId."'></div>";
              }
            }

            $html .= "<div style='clear:both;'></div>"
                   . "<div id='uc-color-attribute-$attrId-selected' class='uc-color-attribute-selected'>&nbsp;</div>"
                   . "</div><!-- /uc-color-attribute-$attrId -->";
            $form['attributes'][$attrId]['#prefix'] = "$html<div id='uc-color-attribute-$attrId-checkboxes' class='uc-color-attribute-checkboxes'>";
            $form['attributes'][$attrId]['#suffix'] = "</div><!-- /uc-color-attribute-$attrId-checkboxes -->";
          }
        }
      }
    }
  }
  return $form;
}

/* Form Submit Hook */
function uc_color_attribute_save($hexValue){
  /* Save value in the database */
  $arg5 = arg(5);
    if(!empty($arg5)){
      if(is_numeric($arg5)){
        db_query("update {uc_color_attribute} set hexValue = '%s' where oid = %d limit 1;",check_plain($hexValue),check_plain($arg5));
      }else{
        $lastId = db_fetch_object(db_query("show table status like '{uc_attribute_options}';"));
        db_query("insert into {uc_color_attribute} (aid,oid,hexValue) VALUES (%d,%d,'%s');",check_plain(arg(3)),$lastId->Auto_increment,check_plain($hexValue));
      }
    }
  return;
}

?>